<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Telegram.Application\Telegram.Application.csproj" />
    <ProjectReference Include="..\Telegram.Persistence\Telegram.Persistence.csproj" />
  </ItemGroup>

</Project>
